export const projects = [
  {
    title: "Movr",
    description:
      "A fullstack movie sharing platform for movie lovers, where users can share their favourite movies for other users to watch.",
    image: "/projects/movr.png",
    year: "2024",
    link: "https://movr.vercel.app",
    github: "https://github.com/maulydev/movr",
    tags: ["Next JS", "Framer Motion", "Tailwind CSS"],
  },
  {
    title: "Open Shortener",
    description:
      "A fullstack open URL Shortener. It provides a simple and efficient way to shorten long URLs, making them easier to share and manage.",
    image: "/projects/opsh.png",
    year: "2023",
    link: "https://opsh.vercel.app",
    github: "https://github.com/maulydev/open-shortener",
    tags: ["Next JS", "Tailwind CSS"],
  },
  {
    title: "Qyro-js landing page",
    description:
      "A lightweight JavaScript library for building static makrdown documentations.",
    image: "/projects/qyro-landing.png",
    year: "2025",
    link: "https://qyro.vercel.app",
    github: "https://github.com/maulydev/qyro-js-landing-page",
    tags: ["Next JS", "Shadcn", "Tailwind CSS"],
  },
  {
    title: "Qyro-js docs template",
    description:
      "A lightweight JavaScript library for building static makrdown documentations.",
    image: "/projects/qyro-js.png",
    year: "2025",
    link: "https://qyro-js.vercel.app",
    github: "https://github.com/maulydev/qyro-js",
    tags: ["Vite", "Typescript", "Tailwind CSS"],
  },
  {
    title: "Gospel Corner",
    description:
      "A blog website for sharing the gospel and inspirational messages.",
    image: "/projects/gospel-corner.png",
    year: "2023",
    link: "https://gospelcorner.vercel.app",
    github: "https://github.com/maulydev/gospel-corner",
    tags: ["React JS", "Django Rest Framework", "Tailwind CSS"],
  },
  {
    title: "My Portfolio",
    description: "A portfolio website.",
    image: "/projects/portfolio.png",
    year: "2023",
    link: "https://v2-mauly.vercel.app",
    github: "https://github.com/maulydev/v2.maulydotdev",
    tags: ["React JS", "Framer Motion", "Tailwind CSS"],
  },
  {
    title: "SimpliDB",
    description: "A python package to simplify sqlite3 database operations.",
    image: "/projects/simplidb.png",
    year: "2022",
    link: "https://pypi.org/project/simplidb/",
    github: "https://github.com/maulydev/simplidb",
    tags: ["Python", "SQLite3"],
  },
  {
    title: "GitBoard",
    description: "GitHub profile in colors using github API.",
    image: "/projects/gitboard.png",
    year: "2022",
    link: "https://gitboard-one.vercel.app",
    github: "https://github.com/maulydev/gitboard",
    tags: ["Next JS", "GitHub API", "Tailwind CSS"],
  },
  {
    title: "Coding Blog",
    description:
      "A fullstack blog website for sharing coding tutorials and articles.",
    image: "/projects/coding-blog.png",
    year: "2024",
    link: "https://maulydotdev.vercel.app",
    github: "https://github.com/maulydev/coding-blog",
    tags: ["Next JS", "Tailwind CSS"],
  },
  {
    title: "Tipytools",
    description: "Empowering Open Source Package Development",
    image: "/projects/tipytools.png",
    year: "2024",
    link: "https://tipytools.vercel.app",
    github: "https://github.com/maulydev/tipytools",
    tags: ["React JS", "Tailwind CSS", "Django Rest Framework"],
  },
  {
    title: "Tipy UI Snippet",
    description: "Tipy UI Snippets is a Visual Studio Code extension providing a comprehensive collection of React JSX/TSX code snippets tailored to streamline your development process. These snippets are designed to work seamlessly with Tailwind CSS, allowing you to quickly scaffold React components with Tailwind CSS styling.",
    image: "/projects/tipy-ui.png",
    year: "2023",
    link: "https://marketplace.visualstudio.com/items?itemName=Tipytools.tipy-ui-snippets",
    github: "https://github.com/tipytools/tipy-ui-snippets",
    tags: ["VS Code", "Tailwind CSS", "React Icons"],
  },
  {
    title: "GhostTalk",
    description:
      "A fullstack web app allows a user to share his/her profile link and receive honest feedback from friends and family without revealing their identity.",
    image: "/projects/ghosttalk.png",
    year: "2023",
    link: "https://ghosttalk.netlify.app",
    github: "https://github.com/maulydev/ghosttalk",
    tags: ["React JS", "Django Rest Framework", "Tailwind CSS"],
  },
];
